import fs from 'node:fs'
const root = new URL('../', import.meta.url)
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8').replace(/\r\n/g, '\n')
const part =
  'var playStyle=document.createElement("style");playStyle.textContent=' +
  JSON.stringify(read('client/q-play.css')) +
  ';document.head.appendChild(playStyle);if(ctx.effect)ctx.effect(()=>()=>playStyle.remove());\n' +
  read('client/q-play.part.js')
const out =
  '// Generated by tools/build-client.mjs; edit client/ sources.\n' +
  read('client/main.part.js').replace('/* @include q-play */', part)
if (process.argv.includes('--check')) {
  if (read('client.js') !== out) throw new Error('client.js 需要重新构建')
} else fs.writeFileSync(new URL('client.js', root), out)
